### ISSUE TITLE
Remake Mad Cobra's "Flex"

### ISSUE THREAD

**Issue by yahreen** [yahreen/you-get-the-gist#3]
We need a remake of Mad Cobra's 1992 smash hit, "Flex" which was all about Flexbox!

https://www.youtube.com/watch?v=XAe3sIxcXw0

**Comment by defnotpaul** [comment]
``` css
#mad-cobra {
  display: flex;
}
```
